<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%!
String pageName = "MASC";
String highlight = "3";
String helpfile="";
String cssfile="/css/page/pagelevels.css";
%>

<%@ page errorPage="/jsp/common/gen_error.jsp"%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value="<%= pageName %>" />
<jsp:param name="highlight" value="<%= highlight %>" />
<jsp:param name="helpfile" value="<%= helpfile %>" />
<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>

<jsp:include page="/jsp/includes/mascSidebar.jsp" flush="true">
<jsp:param name="sidebarName" value="Asia/Pacific" />
</jsp:include>
<div id="rightcolumn">
<!-- Content goes here //--> 
<span class="mainheader">
<I>Arabidopsis
</I> Functional Genomics Research in China
</span>


<p>MASC representative: 
<A HREF="mailto:wcyang@genetics.ac.cn">
Wei-Cai Yang</A>, Institute of Genetics and Developmental Biology, Chinese Academy of Sciences
<a href="http://www.genetics.ac.cn/xywwz/main.html">
Chinese Academy of Sciences
</a>
</p>
<hr>
<p>
<p><IMG SRC="/images/redball.gif"> New! Read the <a href="/portals/masc/countries/China_2009.pdf"><u>2009 China MASC report (pdf).</u></a>
<p> Read the <a href="/portals/masc/countries/China_2008.pdf"><u>2008 China MASC report (pdf).</u></a>
<br>Read the <a href="/portals/masc/countries/China_2007.pdf"><u>2007 China MASC report (pdf).</u></a>
<br>Read the <a href="/portals/masc/countries/China_2006.pdf"><u>2006 China MASC report (pdf).</u></a>
</p>

<dl>
<p>
<I>Arabidopsis
</I> research takes place mainly in the Beijing and Shanghai areas, including Peking University, China Agricultural University, Tsinghua University, and Chinese Academy of Sciences (CAS).  Funding for
<I>Arabidopsis
</I> research is improving in China as the National Science Foundation of China (NSFC), the main funding agency for basic research, will double its budget in the next five years.  A new Center for Signal Transduction and Metabolomics (C-STM) using model plants was established at the Institute of Botany, CAS, in 2005. This center will focus on hormone and peptide signaling, secondary metabolites, and plant toxins.
</p>
<p>
On  November 30,  2005, more than 300 participants attended the annual Workshop on  
<I>Arabidopsis
</I> Research held at Peking University in Beijing.
</p>
<p>
A particularly noteworthy event was the <B><A HREF="/news/18thICAR.jsp">18th Annual International Conference on <I>Arabidopsis</I>
Research,</A></B> which was held in Beijing, China from June 20th-23rd, 2007. This was the first time the annual meeting was held
in an Asian country and the meeting had the largest turnout ever. Over 1500 delegates from all over the world participated in the
conference, with nearly half of the attendees from China itself. Five local institutions jointly organized the conference: the
National Institute of Biological Sciences, The Institute of Botany and Institute of Genetics and Developmental Biology of the
Chinese Academy of Sciences, Peking University, and China Agricultural University.

<p> A special issue of the Journal of Integrative Plant Biology dedicated to <I> Arabidopsis</I> research in China was published in January, 2006. Significant progress achieved by Chinese <I>Arabidopsis</I> researchers in broad aspects of plant sciences was reviewed by Professor Zhihong Xu of Peking University.</p>
<p> <b>Other noteworthy projects:</b></p>
<p>In 1999, a joint research team in 
<a href="http://www.pku.edu.cn/ehomepage.htm">
Peking University
</a> and Chinese Agricultural University (Co-PIs: Zhangliang 
Chen, Li-Jia Qu and Weihua Wu) initiated a project for the 
generation of activation tagging lines by using a 35S 
enhancer construct. The project, funded for US$ 3 millions by 
the 
<a href="http://www.most.gov.cn">
Ministry of Science and Technology of China (MOST)
</a>, was completed in 2002. Approximately 80,000 T-DNA lines 
(T1) have been generated by these researchers. In a separate 
effort, also funded by MOST for US$ 350,000 (PI: Jianru Zuo, 
the Institute of Genetics and Developmental Biology, 
<a href="http://www.cashq.gov.cn">
CAS
</a>), an inducible enhancer/promoter was used to generate 
activation tagging lines. The effort, aimed at the generation 
of 130,000 lines, is projected to be completed in 2005. 
Currently T1 seeds for 35,000 lines have been collected.
</p>
<p>In 2002, the 
<a href="http://www.nsfc.gov.cn">
National Natural Science Foundation of China (NSFC)
</a> provided a grant of US$1.5 millions for a major 
international collaborative project, aimed at the proteomic 
characterization and functional studies of approximate 1,600 
<I>Arabidopsis
</I> transcription factors.  The project, headed by 
<a href="http://www.yale.edu/denglab/">
Xing-Wang Deng
</a> (the Peking University-Yale University-CAS Center for 
Plant Molecular Genetics and Agrobiotechnology; the 
<a href="http://www.pyc.pku.edu.cn/">PYC Center
</a>) and Yuxian Zhu (Peking University), will be completed 
in 2005.
</p>
<p>Funding for 
<I>Arabidopsis
</I> functional genomic research is available from MOST (
<a href="http://www.most.gov.cn">
www.most.gov.cn
</a>), NSFC (
<a href="http://www.nsfc.gov.cn">
www.nsfc.gov.cn
</a>), CAS (
<a href="http://english.cas.cn/Eng2003/page/home.asp">
http://english.cas.cn/Eng2003/page/home.asp
</a>) and other sources on a competitive basis.
</p>
</dl>
</div>
<center>Last modified on July 18, 2009</center>                  

<jsp:include page="/jsp/includes/gen_footer.jsp" flush ="true">
<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>
