<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("T-DNA Transformed Lines donated by J. Alonso, W. Crosby and ") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H3><CENTER><B><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 
X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT ALIGN=left>T-DNA
Transformed lines</B><FONT FACE="Times"><BR>
</FONT><B>from J. Alonso, W. Crosby and J. Ecker</B></CENTER></H3>

<P>&nbsp;</P>

<P>This T-DNA population consists of 140,000 lines which have been
utilized by the Ecker laboratory for PCR-based identification of
insertion in specific genes. The lines of the population are
currently being subjected to sequencing of the chromosomal regions
flanking the T-DNA insertions.</P>

<P>These T-DNA lines were generated by vacuum infiltration of
Columbia (Col) plants with Agrobacterium tumefaciens. The vector
employed was pROK2 (Baulcombe et al., 1986, Nature 321:446). Each T1
transformant was grown individually, and equal quantities of T2 seeds
combined to create pools of 10 lines. These pools of seeds were grown
at ABRC to generate the distributed, T3 seed pools.&nbsp;</P>

<P>&nbsp;</P>

<P><B>Sets of pools of 100:</B><FONT FACE="Times"><BR>
<BR>
</FONT><B>CS76502</B>, 100 pools of 100 (first set)<FONT FACE="Times"><BR>
</FONT><B>CS76504</B>, 100 pools of 100 (second set)<FONT FACE="Times"><BR>
</FONT><B>CS76506</B>, 100 pools of 100 (third set)<FONT FACE="Times"><BR>
</FONT><B>CS76508</B>, 100 pools of 100 (fourth set)</P>

<P>&nbsp;</P>

<P><B>Sets of pools of 10:</B><FONT FACE="Times"><BR>
<BR>
</FONT><B>CS76501</B>, 1000 pools of 10 (first set)<FONT FACE="Times"><BR>
</FONT><B>CS76503</B>, 1000 pools of 10 (second set)<FONT FACE="Times"><BR>
</FONT><B>CS76505</B>, 1000 pools of 10 (third set)</P>
<P>
<center>Last modified on October 10, 2001</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
