<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%
  String pageName = "TAIR -Clones/DNA Resources-Other BAC Libraries";
  String cssfile = "/css/page/pagelevels.css";
%>

<%@ page errorPage="/jsp/common/gen_error.jsp"
	import="org.tair.tfc.*,org.tair.querytools.*,org.tair.utilities.*,java.util.*,java.net.*"%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush="true">
	<jsp:param name="pageName" value="<%= pageName %>" />
	<jsp:param name="cssfile" value="<%=cssfile %>" />
	<jsp:param name="id" value="11132" />
</jsp:include>

<jsp:include page="/jsp/includes/clonesSidebar.jsp" flush="true">
	<jsp:param name="sidebarName" value="BAC libraries from other species" />
</jsp:include>

<div id="rightcolumn">


	<!--CONTENT IN HERE -->
	<span class="header">BACs from Close Relatives of Arabidopsis
		thaliana</span>

	<p>
		The ABRC distributes individual BAC clones and whole BAC libraries
		from several species. These can be found using the
		<a href="/servlets/Search?action=new_search&type=dna">TAIR DNA
			search</a>. To find clones, select search for clone and select the name
		of the species in the "search by" drop down menu, or search by clone
		name starts with and enter the prefix for the appropriate library in
		the search box. Libraries can be found selecting search for library,
		and search by library name, then entering the genus and species in the
		search box.
	</p>



	<p>
		Individual BAC clones from the following species are available:
	</p>

	<p>
		<a href="/servlet/TairObject?id=500300027&type=library">Arabidopsis
			arenosa</a> (prefix AER)
		<br />
		<a href="/servlet/TairObject?id=500300039&type=library">Arabidopsis
			lyrata</a> (prefix ALY)
		<br />
		<a href="/servlet/TairObject?id=500300029&type=library">Capsella
			rubella</a> (prefix CR)
		<br />
		<a href="/servlet/TairObject?id=500300030&type=library">Sysimbriumi
			rio</a> (prefix SIR)
		<br />
		<a href="/servlet/TairObject?id=500300028&type=library">Olimarabidopsis
			pumilla </a> (prefix OPM)
	</p>
	<p>
		Complete libraries generated by Tom Mitchell-Olds from the following
		species are available:
	</p>

	<p>
		<a href="/servlet/TairObject?id=500300033&type=library">Arabidopsis
			cebennensis</a>
		<br />
		<a href="/servlet/TairObject?id=500300035&type=library">Arabidopsis
			halleri</a>
		<br />
		<a href="/servlet/TairObject?id=500300034&type=library">Arabidopsis
			lyrata</a>
		<br />
		<a href="/servlet/TairObject?id=500300036&type=library">Capsella
			rubella</a>
		<br />
		<a href="/servlet/TairObject?id=500300032&type=library">Cleome
			spinosa</a>
		<br />
		<a href="/servlet/TairObject?id=500300037&type=library">Tropaeolum
			majus</a>
	</p>
	<p style="text-align: center"> Last modified on March 18, 2011</p>

</div>
<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true">
	<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>
