<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("Random GFP::cDNA Fusion T-DNA Transformants from David Ehrhardt") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H2><CENTER><B><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT ALIGN=left>Random
GFP::cDNA Fusion T-DNA Transformants</B><FONT FACE="Times"><B><BR>
</B></FONT><B>from David Ehrhardt</B></CENTER></H2>

<P>&nbsp;</P>

<P>T-DNA lines for which the transforming vector (pEGAD) includes a
CaMV 35S promoter-driven GFP coding region, fused to random clones
from an Arabidopsis cDNA library, were generated by David Ehrhardt,
Sean Cutler and Chris Somerville. The resulting lines express GFP in
varying patterns as influenced by the localization/targeting effects
of the gene products of the various cDNAs. The description of pEGAD
is available on the Carnegie Web site (<A HREF="http://deepgreen.stanford.edu">deepgreen.stanford.edu</A>),
as is a gallery of images documenting the various patterns of GFP
expression among the lines. The pEGAD plasmid used for
transformations (CD3-389) is also currently available.</P>

<P>There are 108 lines available for distribution, each of which is
the product of an independent transformation event using the vector
library. A "Basic Set" of 16 lines has been organized on the basis of
varying, patterns of GFP expression. Characterizations of the
Arabidopsis gene of the T-DNA insertion, for lines having results, as
well as links to the Carnegie Web site are included in the details of
the stocks.</P>

<P>The selective agent for transformed plants is the herbicide Basta.
The background employed for the transformations is Col-2 (CS907), and
is included in the organized sets. Reference: Sean Cutler, David
Ehrhardt, Joel Griffitts and Chris Somerville (1999) Random GFP:cDNA
fusions enable visualization of subcellular structures in cells of
Arabidopsis at high frequency. PNAS 97: 3718-3723.</P>

<P>&nbsp;</P>

<CENTER><B>Sets of GFP lines:</B>

<P><TABLE BORDER=1 WIDTH=400>
   <TR>
      <TD VALIGN=top WIDTH=102>
         <CENTER><B>Stock#</B></CENTER>
      </TD>
      <TD VALIGN=top WIDTH=273>
         <CENTER><B>Donor#</B></CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top WIDTH=102>
         <CENTER>CS84722</CENTER>
      </TD>
      <TD VALIGN=top WIDTH=273>
         <CENTER>Full set of 108 lines (includes Basic Set of 16
         lines)</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top WIDTH=102>
         <CENTER>CS84723</CENTER>
      </TD>
      <TD VALIGN=top WIDTH=273>
         <CENTER>Basic Set of 16 lines</CENTER>
      </TD>
   </TR>
</TABLE>
</P></CENTER>

<P>&nbsp;</P>

<CENTER><B>Individual lines comprising the basic set of 16:</B>

<P><TABLE BORDER=1 WIDTH=400>
   <TR>
      <TD VALIGN=top>
         <CENTER><B>Stock#</B></CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER><B>Donor#</B></CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84725</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>060798A / Q8</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84726</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>29-1</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84727</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>110898E / Q5</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84728</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>060798B / Q4</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84729</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>020898A / Q10</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84730</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>38-3</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84731</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>110898F / N7</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84732</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>060798C / LE8</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84733</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>m253</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84734</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>36-30</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84735</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>060798D / A5</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84736</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>050598A / V6</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84738</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>39-19</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84739</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>39-10</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84740</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>mc-1</CENTER>
      </TD>
   </TR>
   <TR>
      <TD VALIGN=top>
         <CENTER>CS84741</CENTER>
      </TD>
      <TD VALIGN=top>
         <CENTER>200798A / N1</CENTER>
      </TD>
   </TR>
</TABLE>
</P>

<P>&nbsp;</P>

<P></P></CENTER>
<P>
<center>Last modified on August 29, 2001</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
