<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("Institute for Molecular Agrobiology  (IMA ) lines donated to ABRC") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H2><CENTER><B><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT ALIGN=left>Institute
of Molecular Agrobiology (IMA) lines </B><FONT FACE="Times"><BR>
</FONT><B>from </B>V. Sundaresan and colleagues</CENTER></H2>

<P>&nbsp;</P>

<P>The IMA Ds Insertion transposant lines were generated by Prof. V.
Sundaresan and colleagues from the National University of Singapore.
The chromosomal regions flanking the insertions have been sequenced,
and the sequences deposited in GenBank. The full text of the
associated paper (<A HREF="http://www.ncbi.nlm.nih.gov:80/entrez/query.fcgi?cmd=Retrieve&db=PubMed&list_uids=10590156&dopt=Abstract">The
Plant Cell, 11: 2263-2270</A>) is available from the Plant Cell
e-journal site and is Copyright(c) by the American Society of Plant
Physiologists. The transposon system of Sundaresan et al. (1995) was
employed to generate these lines.</P>

<P>These Arabidopsis thaliana (Landsberg erecta background) lines
contain mostly single copy insertions of modified maize transposable
Dissociation (Ds) elements inserted into different positions within
the genome.</P>

<P>Each Ds element carries a NPTII gene, and therefore plants with Ds
insertions are resistant to kanamycin. The Ds elements in these lines
are stable, but capable of remobilization if the Ac transposase is
provided, e.g., by crossing with one of the Ac starter lines (CS8043
&endash; 8049). Ds elements also carry the GUS reporter gene designed
to act as gene trap (SGT or GT) or enhancer trap (SET).</P>

<P>Sequences flanking the Ds insertions in the following transposant
lines were amplified using TAIL-PCR. Sequences were analyzed by BLAST
searches in two public databases: NCBI GenBank and Arabidopsis
GenBank in Stanford. For further details please see Parinov et al.
(1999).</P>

<P>&nbsp;</P>

<H3><CENTER><B>Ordering IMA lines - Material Transfer Agreement (MTA)
required</B></CENTER></H3>

<P>All lines require a Material Transfer Agreement (MTA). This needs
to be received by ABRC before seeds can be sent. Please send
completed agreements to: Arabdopsis Biological Resource Center, OSU, 1060 Carmack Road, Columbus, OH, 43210, USA. Please note that MTAs can
not be sent by FAX.</P>

<P>&nbsp;</P>

<P><B>Important Information on completing the MTA associated with the
IMA lines: </B></P>

<P>There are two forms of the MTA from which to choose. The two are
the same except that <A HREF="IMAMTA_ABRC.pdf">Form 1</A> has a
clause (#9) regarding rule of the law of Singapore, which is deleted
from <A HREF="IMAMTA_ABRC_omit9.pdf">Form 2</A>. You should use Form
1 unless your institution will not allow clause #9 to be
included.</P>

<P><B>Neither MTA can be altered.</B> Any questions about governing
law can be directed to Professor Venkatesan Sundaresan at:
director@ima.org.sg</P>

<P>&nbsp;</P>

<P><A HREF="IMAMTA_ABRC.pdf">MTA for IMA stocks - Form 1</A>,
includes Clause 9 (rule of Singapore law).</P>

<P><A HREF="IMAMTA_ABRC_omit9.pdf">MTA for IMA stocks - Form 2</A>,
Clause 9 crossed out (rule of Singapore law).</P>

<P>&nbsp;</P>

<P>Regarding section two on page one of MTAs:</P>

<P>'In response to the RECIPIENT's request for the BIOLOGICAL
MATERIAL that has been deposited by PROVIDER at Arabidopsis
Biological Resource Center (ABRC), USA, and identified as
__XXXXXX___________'</P>

<P>In this section, where we have placed the XXXXXX, you need to
state the ABRC stock number you are going to use. This space is
intended for a description of the BIOLOGICAL MATERIAL.</P>

<P>Unfortunately we can not send out the material if this section is
left blank, or if it contains a name or an address, or is
non-specific. If you require a large number of lines, then our
suggestion would be to fill in the space with the text: 'identified
as ___defined below___'</P>

<P>- and then to list the lines on the bottom of page 1 or 3 of the
MTA as follows:</P>

<P>BIOLOGICAL MATERIAL: CSxxx CSyyy CSzzz.</P>

<P>The list MUST however be on one of the three pages of the MTA and
NOT as a separate page. Another alternative would be to fill out
additional MTAs for blocks of 3-4 lines if that is more convenient or
acceptable to you.</P>

<P>&nbsp;</P>

<H3><CENTER><B>How to find your gene in the
database</B></CENTER></H3>

<P>Identify the GenBank indentification numbers (gi/gid) of sequences
in GenBank identical to your sequence:</P>

<P>Run a BLASTN search with the nucleotide sequence of your gene at
http://www.arabidopsis.org/blast/, and record the names or gi/gid
numbers of the GenBank entries that are identical to your gene Search
the ima page for these names/gid numbers. Use the "Find" (Ctrl-F)
option on your Internet browser to search for matches within the
table on the ima lines web page. Try all names and/or numbers (BAC
and P1 clones, BAC Ends, EST and other nucleotide entries of GenBank)
that are identical to your gene of interest since only one of them
may be represented in this database (preference is given to BAC and
P1 clones). This will reveal seed lines with insertions in your
gene.</P>

<P>IMPORTANT: Up to 7% cross-contamination in the sequencing data has
been detected in the lines, that result mainly from
PCR-contamination, but also occasionally from seed contamination.
Since the flanking sequence data was obtained from single runs each
line has to be independently confirmed. This confirmation is
accomplished most simply by performing PCR amplification of DNA from
the line, using gene specific primers and Ds-specific primers. The
presence of PCR products of the correct size on a gel is usually
sufficient confirmation, although sequencing of the products can be
performed if necessary.</P>

<P>&nbsp;</P>

<P><B>Primers</B></P>

<P>The following primers complimentary to the ends of Ds element can
be used for PCR amplification. Distance from the 5'-end of each
primer to the corresponding end of transposon is indicated.</P>

<P>For 3'-end of Ds:</P>

<P>Ds3'-1 ggTTCCCgTCCgATTTCgACT 179 bp</P>

<P>Ds3'-2 CgATTACCgTATTTATCCCgTTC 131 bp</P>

<P>Ds3'-3 TCgTTTCCgTCCCgCAAgT 82 bp</P>

<P>&nbsp;</P>

<P>For 5'-end of Ds:</P>

<P>Ds5'-1 ACggTCgggAAACTAgCTCTAC 173 bp</P>

<P>Ds5'-2 TCCgTTCCgTTTTCgTTTTTTAC 114 bp</P>

<P>Ds5'-3 CggTCggTACgggATTTTCC 39 bp</P>

<P>&nbsp;</P>

<P><B>References</B></P>

<P>Sundaresan, V., Springer, P., Volpe, T., Haward, S., Jones, J.D.,
Dean, C., Ma, H., and Martienssen, R. (1995). Patterns of gene action
in plant development revealed by enhancer trap and gene trap
transposable elements. Genes Dev. 9, 1797-1810.</P>

<P>Liu, Y.G., and Whittier, R.F. (1995). Thermal asymmetric
interlaced PCR: automatable amplification and sequencing of insert
end fragments from P1 and YAC clones for chromosome walking. Genomics
25, 674-681.</P>

<P>Parinov, S., Sevugan, M., Ye, D., Yang, W.-C., Kumaran, M., and
Sundaresan, V. (1999) Analysis of Flanking Sequences from Ds
Insertion Lines: A Database for Reverse Genetics in Arabidopsis.
Plant Cell 11, 2263-2270.</P>
<P>
<center>Last modified on May 18, 2004</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
