<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<%String pageName = "TAIR -Clones/DNA Resources-Libraries";
String cssfile="/css/page/pagelevels.css";
%>

<%@ page
errorPage="/jsp/common/gen_error.jsp"
import="org.tair.tfc.*,org.tair.querytools.*, org.tair.utilities.*,java.util.*, java.net.*"
%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value="<%= pageName %>" />
<jsp:param name="cssfile" value="<%=cssfile %>" />
<jsp:param name="id" value="1113" />
</jsp:include>

<jsp:include page="/jsp/includes/clonesSidebar.jsp" flush="true">
<jsp:param name="sidebarName" value="Libraries" />  
</jsp:include>

<div id="rightcolumn">


<!-- CONTENT IN HERE -->

<a name="top"></a>
<span class="header">Libraries</span>

<p>Use the quick links in the menubar to the left to find more about each type of library available from the ABRC.</p>

<p>cDNA libraries, including two-hybrid libraries for interaction cloning, and genomic libraries, including some in plant transformation vectors, are available from ABRC. Most YAC libraries have now been archived, but are still available upon request. Many BAC libraries are available only as individual clones or colony blot filters. BAC libraries from close relatives of Arabidopsis thaliana have been received from Daphne Preuss and Tom Mitchell Olds. Libraries and colony blot filters generated by Dapne Preuss are available from Amplicon and individual clones are available from ABRC. Libraries generated by Tom Mitchell Olds are currently archived, but can be obtained from ABRC upon request.</p>
</div>
<jsp:include page="/jsp/includes/gen_footer.jsp" flush ="true">
<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>

