<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("TAIR") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("0") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H3><CENTER><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 
X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT ALIGN=left>Recombinant
Inbred lines <FONT FACE="Times"><BR>
</FONT>from <B>Drs. O. Loudet and S. Chaillou</B></CENTER></H3>

<P>&nbsp;</P>

<P>This Bay-0 x Shahdara recombinant inbred line population has been
generated by Olivier Loudet and Sylvain Chaillou between 1997 and
2000 at INRA Versailles (France).</P>

<P>The 411 recombinant inbred lines were derived from a cross between
the ecotypes Bay-0 and Shahdara, using Bay-0 as the female parent.
Bay-0 originates from a fallow-land habitat near Bayreuth in Germany
(accession CS954), whereas Shahdara originates in the Pamiro-Alay
mountains in Tadjikistan (accession CS929).  Bay-0 and Shahdara
ecotypes were chosen because of their known geographical, ecological
and genetic distances.</P>

<P>Lines were conducted through Single Seed Descent until F6
generation without selection. Then one plant per line was used for
genotyping and selfed to obtain F7 seeds. The seeds available are F8
seeds from bulk multiplication of F7 plants.</P>

<P>Complete description of the population can be found in Loudet et
al., 2002 (Theoretical and Applied Genetics, vol 104, pp 1173-1184).
For more information (RIL names, genetic map, marker data, studied
traits, phenotypic data) see the <A HREF="http://www.inra.fr/qtlat/">Versailles
QTL Arabidopsis web site</A>.</P>

<P>&nbsp;</P>

<P><B>Stock#:</B><FONT FACE="Times"><B><BR>
</B></FONT><B>CS57920</B>, compete set of 411 lines, including
parental lines</P>

<P>&nbsp;</P>

<P><B>CS57921</B>, Core-Pop165 set, including parental lines</P>

<P>This set of 165 lines is intended for mapping new markers and for
optimised QTL mapping when using all 411 lines is impractical. This
minimal core set was designed using the MapPop tool from D. Brown and
T. Vision:- Vision TJ, Brown DG, Shmoys DB, Durrett RT and Tanskley
SD (2000) Selective mapping: A strategy for optimizing the
construction of high-density linkage maps. Genetics 155:407-420</P>

<P>This set includes the following donor numbers:</P>

<P>003; 007; 013; 015; 017; 018; 019; 022; 024; 030; 032; 034; 035;
037;<FONT FACE="Times"> </FONT>044; 045; 047; 048; 049; 053;
<FONT FACE="Times"><BR>
</FONT>055; 058; 059; 061; 062; 065; 067; 069;<FONT FACE="Times">
</FONT>070; 071; 073; 077; 078; 081; 083; 084; 090; 092; 094; 097;
<FONT FACE="Times"><BR>
</FONT>098; 099;<FONT FACE="Times"> </FONT>100; 101; 102; 104; 106;
110; 111; 112; 114; 116; 118; 120; 121; 123;<FONT FACE="Times">
</FONT>126; 127; 129; 131; <FONT FACE="Times"><BR>
</FONT>133; 134; 135; 136; 137; 140; 143; 146; 147; 149;<FONT FACE="Times">
</FONT>150; 155; 157; 162; 165; 170; 173; 175; 176; 179; <FONT 
FACE="Times"><BR>
</FONT>180; 183; 186; 187;<FONT FACE="Times"> </FONT>190; 191; 194;
195; 197; 198; 199; 200; 202; 204; 210; 211; 214; 220;<FONT FACE="Times">
</FONT>232; 234; <FONT FACE="Times"><BR>
</FONT>236; 240; 248; 252; 256; 262; 264; 267; 271; 273; 274; 279;
286; 289; 298; 300; 302; 305; 306; 308; <FONT FACE="Times"><BR>
</FONT>309; 314; 319; 320; 325; 326; 328; 329; 330; 334; 335; 336;
342; 343; 345; 349; 351; 357; 358; 359; <FONT FACE="Times"><BR>
</FONT>362; 363; 364; 365; 368; 376; 378; 379; 380; 381; 382; 387;
388; 390; 394; 398; 400; 402; 409; 410; <FONT FACE="Times"><BR>
</FONT>412; 413; 421; 424; 430</P>

<P>&nbsp;</P>

<P><B>CS57922</B>, Core-Pop18 set, including parental lines</P>

<P>This set of 18 lines is NOT intended for any markers or QTL
mapping, but rather to give an idea of the variability and
transgression of any specific trait in the Bay-O x Shahdara
population using a small number of lines (together with the parents).
This set was also designed with the MapPop tool to  ensure that the
lines represent the maximum of the variability of the population.</P>

<P>This set includes the following donor numbers:</P>

<P>007; 030; 045; 092; 094; 098; 136; 137; 162; 173; 175; 194; 279;
298; 329; 343; 349; 390</P>
<P>
<center>Last modified on November 19, 2002</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
