<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("Saskatoon collection of activation tagged T-DNA insertion lines") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H3><CENTER><B><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 
X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT 
ALIGN=left>Saskatoon collection of activation tagged T-DNA insertion lines</B></CENTER></H3>

<CENTER>&nbsp;</CENTER>

<p>
The Saskatoon (SK) collection was generated by Stephen Robinson &
Isobel Parkin at the Agriculture and Agri-Food Canada, Saskatoon
Research Centre, Canada. The wild-type Columbia (Col-4) was
transformed with the binary vector pSKI015 using the A. tumefaciens
strain GV3101 according to the floral dip method with the addition of
a vacuum infiltration step subsequent to submersion of the plants in
the GV301 culture, when a vacuum of 500 mm/Hg was applied. Primary
transformants (T1) were selected using the herbicide glufosinate
ammonium (Basta), then transplanted and maintained as individual
lines. In total, 49,160 T1 activation tagged lines were generated from
which T2 seed was archived and T3 lines were obtained by single-seed
descent. Single seed descent with continued selection was employed to
generate a population of 44,383 T3 families that are enriched for
homozygous mutant genotypes. Plant tissue was collected from each T2
line and DNA was extracted using a CTAB method.
</p>
 
<p>
The number of independent insertion events per line was estimated
initially by assessing the segregation ratio for herbicide resistance
scored in the progeny from 100 T1 plants. This resulted in an estimate
of 1.35 insertion loci/ line suggesting the entire population may
contain ~70,000 independent T-DNA integration events. However,
Southern analysis of 102 lines suggested a greater number of actual
integration events (3.1 T-DNA insertions/ line) with a high percentage
(~82%) of the insertion alleles being the result of complex T-DNA
integrations events. This was later confirmed through sequence
analysis of the DNA flanking the TDNA left border, which is in
contrast with the lower frequency of T-DNA integration reported in
previously characterized populations.
</p>
 
<p>
Regarding the genomic distribution of flanking sequence tags (FSTs),
TAIL-PCR was employed as a relatively efficient high throughput
strategy to amplify the sequence flanking the T-DNA insertion events
(FST) present in the mutagenised population. The genetic origin of
16,428 FST sequences derived from DNA flanking the left border of
stably inherited T-DNA molecules was determined by analysing the
sequence from amplification products generated from 28,908 individual
T2 lines. The genomic location of the integrated T-DNA molecules was
determined by aligning each FST sequence with the five nuclear and two
extra-nuclear A. thaliana pseudo chromosomes. The T-DNA integration
sites were classified based on the available annotation (TAIR8;
<a href="http://www.arabidopsis.org">http://www.arabidopsis.org</a>) and the frequency of integration in
promoter, 5'-UTR, exon, intron, 3'-UTR and intergenic regions was
determined
</p>
 
<p>
This population is an excellent tool for both reverse and forward
genetic screens and has been used successfully to identify a number of
novel mutants. FST have been generated and mapped for 15,507 lines to
enable further application of the population, while providing a clear
distribution of T-DNA insertions across the genome. The population is
being screened for a number of biochemical and developmental
phenotypes. The population provides an additional tool for plant
researcher's to assist with determining gene function for the many as
yet uncharacterized genes annotated within the Arabidopsis genome
sequence. The presence of enhancer elements on the inserted T-DNA
element allows both knock-out and dominant activation phenotypes to be
identified for traits of interest. For more details see
<a href="http://aafc-aac.usask.ca/FST">http://aafc-aac.usask.ca/FST</a> and Robinson SJ, Tang LH, Mooney BA,
McKay SJ, Clarke WE, Links MG, Karcz S, Regan S, Wu YY, Gruber MY, Cui
D, Yu M, Parkin IA. An archived activation tagged population of
Arabidopsis thaliana to facilitate forward genetics approaches. BMC
Plant Biol. 2009 9:
101. (<a href="http://www.biomedcentral.com/1471-2229/9/101">http://www.biomedcentral.com/1471-2229/9/101</a>).
</p>

<P>
<center>Last modified on December 8, 2009</center>
</p>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
