<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("T-DNA lines from M. Sussman and R. Amasino for forward ") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>
<H3><CENTER><IMG SRC="/images/abrc.gif" WIDTH=86 HEIGHT=30 
X-CLARIS-USEIMAGEWIDTH X-CLARIS-USEIMAGEHEIGHT ALIGN=left><B>T-DNA
lines from M. Sussman and R. Amasino</B></CENTER></H3>

<P>&nbsp;</P>

<P>This is a group of 37,800 lines for forward screening assembled
from the first T-DNA population of the Arabidopsis Knockout Facility.
This stock is distributed as 168 pools of 225 lines each. These T-DNA
pools were generated by the Agrobacterium vacuum infiltration
technique using a derivative of the pD991 vector from Dr. Thomas
Jack. The genetic background for this stock is Ws-2 (CS2360, included
with this stock). Please consult the Arabidopsis Knockout Facility
web site for details. The vector of these lines carries an Ap2::GUS
construction, and expression of GUS in shoots may be observed.</P>

<P>Please note that there are ordering restrictions on these stocks:
ABRC is not allowed to send the seeds to any private company.</P>

<P>&nbsp;</P>

<P><B>Stock#:</B><FONT FACE="Times"><BR>
</FONT><B>CS22830</B>, 168 pools of 225 lines each</P>
<P>
<center>Last modified on October 10, 2001</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
