<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>

<%@ page import="java.net.URLEncoder" %>
<%@ page errorPage="/jsp/common/gen_error.jsp"%>
<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value='<%= URLEncoder.encode("ABRC TAIR Home Page") %>' />
<jsp:param name="highlight" value='<%= URLEncoder.encode("7") %>' />
<jsp:param name="helpfile" value='<%= URLEncoder.encode("") %>' />
</jsp:include>

<span class="header">Salk Sequence-indexed T-DNA Lines at ABRC & NASC</span>
 </TD></TR></table>
<p>
<p>
<table width="602" align="center" border="0" cellspacing="0" cellpadding="0">

<TR><td>

<BR>The Arabidopsis Biological Resource Center (ABRC) and the Nottingham
Arabidopsis Stock Centre (NASC) have released the first set of single
T-DNA lines received from Dr. Joseph Ecker, The Salk Institute, La
Jolla, CA.  These stocks can be found and ABRC orders placed in TAIR:
<p><a href="/servlets/SeedSearcher">/servlets/SeedSearcher</a>
<p>
In addition, the flanking sequences of the T-DNA insertion sites in these lines are available via TAIR's BLAST server where each sequence is linked to the Stock detail page and corresponding locus (if the insertion lies within a gene):

    <p><a href="/Blast">/Blast</a>
    <p>
and the multi-FASTA file is downloadable from TAIR's FTP site:
    <p><a href="ftp://ftp.arabidopsis.org/home/tair/Sequences/blast_datasets/">ftp://ftp.arabidopsis.org/home/tair/Sequences/blast_datasets/</a>
        <p>
<P>
<BR>The stocks received are SALK_000001 through SALK_006432.  Note that
the stock numbers for these are all of the form SALK_xxxxxx, the same
as the Salk Institute Genomic Analysis Laboratory (SIGnAL) accession
numbers for all of the lines.  This numbering convention is being
employed so that a common identifier will be associated with the
lines for the stock centers, database and the various experimental
formats in which these stocks will be utilized.
<P>
<BR>These stocks are single, segregating flank-tagged T3-generation T-DNA
lines generated by vacuum infiltration of Columbia (Col) plants with
Agrobacterium tumefaciens vector pROK2.  Kanamycin is employed for
selection of plants having T-DNA insertions. DNA sequencing was
performed on plants for the same sample of seeds that are being
distributed. Investigators should  confirm the presence of the T-DNA
insertion in the gene  by PCR using primers from the T-DNA
Left-border and the target gene sequence. For more detailed
information see the <a href="http://signal.salk.edu/tdna_protocols.html">SIGnAL web site</a>
(http://signal.salk.edu/tdna_protocols.html).
<P>
<BR>Sequence reactions will be performed on over 140,000 lines of this
population during the next 24 months.  About 6,000 new lines will be
sequenced and subsequently released by the stock centers each month.
At the time of sequencing, samples of seeds from each line will be
transmitted to the stock centers in quantities for distribution.
Since distribution-level quantities of the stocks are being received,
all lines will be made available for distribution within 30 days of
receipt by the stock centers. Please check the TAIR and the NASC
database for availability of lines.  Absence of a line from these
databases means that the seeds are not available.  The only seed
distribution points for this resource are ABRC and NASC.  SIGnAL will
not distribute lines to individual laboratories.  At least one line
of each gene actually identified as having an insertion in the
population will be grown at the stock centers so that maximum seed
distribution will be ensured. T-DNA insertion site sequence
annotation and the genomic locations of all the sequenced index T-DNA
insertions can be found by searching the T-DNAExpress database
(http://signal.salk.edu/cgi-bin/tdnaexpress). Also, please refer to
the "Frequently Asked Questions" page on the SIGnAL web site before
contacting SIGnAL , ABRC or NASC about this resource.
<P>    

<P>
<center>Last modified on October 30, 2001</center>

<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true" />
