<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%
  String pageName = "TAIR- Proteome Resources- Protein-protein Interaction";
  String cssfile = "/css/page/pagelevels.css";
%>

<%@ page errorPage="/jsp/common/gen_error.jsp"
	import="org.tair.tfc.*,org.tair.querytools.*,org.tair.utilities.*,java.util.*,java.net.*"%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush="true">
	<jsp:param name="pageName" value="<%= pageName %>" />
	<jsp:param name="cssfile" value="<%=cssfile %>" />
	<jsp:param name="id" value="11804" />
</jsp:include>

<jsp:include page="/jsp/includes/proteomeSidebar.jsp" flush="true">
	<jsp:param name="sidebarName" value="Protein-protein Interaction" />
</jsp:include>

<div id="rightcolumn">


	<!-- CONTENT IN HERE -->
	<span class="mainheader">Protein-protein interaction</span>

	<DL>
		<!--
<DT> <a href="http://www.bind.ca/Action">BIND (Biomolecular Interaction 
Network Database)</a></DT>
<dd> Protein-protein interaction data from many organisms including Arabidopsis. Contains user submitted high-throughput data and in-house hand-curated information gathered from the scientific literature.</dd>
<DT> <a href="ftp://ftp.arabidopsis.org/home/tair/Proteins/">Arabidopsis Predicted Interactome</a></DT>
<dd>A set of 20,000 protein-protein interactions for the Arabidopsis proteome. This dataset is entirely based on ortholog matching by InParanoid, and using yeast, fly, worm and human Interactome datasets.</dd>
-->

		<DT>
			TAIR
		</DT>
		<dd>
			TAIR has Arabidopsis protein-protein interaction data curated from
			the literature by TAIR curators. The data is currently available as a
			tab-delimited text file (
			<a href="ftp://ftp.arabidopsis.org/home/tair/Proteins/">download</a>).
			They will be made searchable from the TAIR web site in the future.
		</dd>

		<DT>
			<a href="http://www.ebi.ac.uk/intact/site/index.jsf"> IntAct of
				EMBL-EBI</a>
		</DT>
		<dd>
			IntAct provides protein-protein interaction data from many organisms,
			including Arabidopsis. All interactions are derived from literature
			curation or direct user submissions. Can be searched and graphically
			viewed. All data can be downloaded as a tab-delimited text file, or
			in the standard PSI-MI XML format.
		</dd>

		<DT>
			<a href="ftp://ftp.arabidopsis.org/home/tair/Proteins/">Arabidopsis
				Predicted Interactome</a>
		</DT>
		<dd>
			This is a compressed Excel file provided by
			<a
				href="http://www.science.siu.edu/plant-Biology/BioPages/Geisler.bio.html">Matt
				Geisler</a> at Southern Illinois University. It consists of a set of
			20,000 protein-protein interactions for Arabidopsis forming a
			preliminary dataset for an interactome. This dataset is entirely
			based on ortholog matching by InParanoid, and using yeast, fly, worm
			and human interactome datasets. Refer to the
			<a href="ftp://ftp.arabidopsis.org/home/tair/Proteins/Protein.README">
				README</a> file for more details.
		</dd>

		<dt>
			<a href="http://bar.utoronto.ca/interactions/">Arabidopsis
				Interactions Viewer </a>
		</dt>
		<dd>
			The Arabidopsis Interactions Viewer queries a database of predicted
			and confirmed Arabidopsis interacting proteins. The predicted
			interactions &#040;interologs&#041; were generated by Drs Matt
			Geisler and Jane Geisler-Lee at the Southern Illinois University. The
			confirmed Arabidopsis interacting proteins come from BIND, the
			Biomolecular Interaction Network Database and from high-density
			Arabidopsis protein microarrays &#040;Popescu et al, 2007; Popescu et
			al, 2009&#041; and other literature sources. This tool is developed
			and maintained by the Provart Laboratory at the University of
			Toronto.
		</dd>

		<dt>
			<a href="http://bioinfo.esalq.usp.br/atpin">AtPIN (Arabidopsis
				thaliana protein interaction network) </a>
		</dt>
		<dd>
			Arabidopsis thaliana protein interaction network was built and is
			maintained by the Laborat&oacute;rio de Biologia Molecular de Plantas
			at Agriculture School from Sao Paulo University - Brazil. The
			interactions database includes all interactions present at the
			Arabidopsis thaliana Protein Interactome Database, the Predicted
			Interactome for Arabidopsis, Arabidopsis protein-protein interaction
			data curated from the literature by TAIR curators, BIOGRID and
			IntAct.
		<dd>
		<dt>
			<a href="http://gmdd.shgmo.org/Computational-Biology/ANAP/">ANAP
				(Arabidopsis Network Analysis Pipeline)</a>
		</dt>
		<dd>
			ANAP has been developed for Arabidopsis protein interaction
			integration and network-based study, to facilitate functional protein
			network analysis (
			<a href="http://www.ncbi.nlm.nih.gov/pubmed/22345505">PMID:22345505</a>).
			ANAP integrates 11 Arabidopsis protein interaction databases,
			comprising 201,699 unique protein interaction pairs, 15,208
			identifiers (including 11,931 TAIR AGI codes), 89 interaction
			detection methods, 73 species that interact with Arabidopsis and
			6,161 references.
		<dd>
	</DL>

</div>
<jsp:include page="/jsp/includes/gen_footer.jsp" flush="true">
	<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>

