<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ page contentType="text/html; charset=UTF-8" %>
<%!
String pageName = "Browse";
String cssfile="/css/page/pagelevels.css";
%>


<%@ page import="org.tair.tfc.*,org.tair.querytools.*, org.tair.utilities.*,java.util.*, java.net.*"
errorPage="/jsp/common/gen_error.jsp"%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value="<%= pageName %>" />
<jsp:param name="cssfile" value="<%= cssfile %>" />
<jsp:param name="id" value="62" />
</jsp:include>

<jsp:include page="/jsp/includes/browseSidebar.jsp" flush="true">
<jsp:param name="sidebarName" value="Monsanto SNP and Ler Collections" />
</jsp:include>

<div id="rightcolumn">


<SPAN class="mainheader">Monsanto Arabidopsis Polymorphism and Ler Sequence Collections</SPAN>
<!-- CONTENT IN HERE -->
<dl><dt>
<dd>
The activities previously handled by Cereon Genomics, a wholly-owned
subsidiary of Monsanto Company, were relocated to St. Louis, Missouri on June 30, 2002.  Any Agreements
 entered into with Cereon Genomics are now administered
by Monsanto Company.  This website text has been changed to substitute
Monsanto Company in place of any references to Cereon Genomics.
<P>
This page provides access to a collection of predicted Arabidopsis single-nucelotide polymorphisms (SNP)
 and small insertions/deletions (INDELs) between the publicly available Columbia (Col) sequence and 
Landsberg erecta (Ler) sequence generated by Monsanto. In addition to the polymorphisms, the Ler sequence
 has recently been released. The data have been kindly submitted by Dr. Steve Rounsley.
<P>
These data are accessible only to non-profit institutions, universities, and colleges. In order to access
 the data users must first fill out a one-time <B>Registration</B> form for the Polymorphism data or the
 Ler Sequence data, respectively, to get access to each data set. Registered users must then <B>Login</B> 
to access the data that they have registered for. If a user has registered for one data set, the same login 
information can be used for the other set, if the user agrees to the registration agreement for the second 
data set.
</P>

<P><B>To access Polymorphism:</B> </P>
<P><B>First time Monsanto users:  <A href="<%= WebApp.getSecureServerURL() %>/cgi-bin/cereon/cereon_register.pl">Register here</A></b><BR> 

<B>Registered (for either Polymorphism or Ler Sequence) users:  <A href="<%= WebApp.getSecureServerURL() %>/cgi-bin/cereon/cereon_login.pl">Login here</A></B></P>

<P>

<A href="/browse/Cereon/help.jsp">Polymorphism Releases</A>.
There are now 37,344 SNPs, 18,579 InDels, and 747 Large Indels, a total of 56,670 polymorphisms.

</P>

<P>
<B>To access Ler Sequence:</B> 
</P>



<P>
<B>First time Monsanto users:     <A href="<%= WebApp.getSecureServerURL() %>/cgi-bin/cereon/cereon_seq_register.pl">Register here</A></B><BR>

<B>Registered (for either Polymorphism or Ler Sequence) users:    <A href="<%= WebApp.getSecureServerURL() %>/cgi-bin/cereon/cereon_seq_login.pl">Login here</A></B>
</P>

<P>
<A href="/browse/Cereon/help_seq.jsp">Ler Sequence Release</A>.
There are 81,306 sequence entries from a single-pass shotgun sequencing. It contains approximately 95 Mb of sequence.

</P>

<P><B>Warning:</B> Access to Monsanto Information is <B>limited to non-profit or
educational institutions for use in noncommercial research only</B>. Please be
aware that any disclosure, copying or use of the contents of Monsanto
Information by a commercial entity is prohibited.  Monsanto will pursue all
legal and equitable remedies for any improper use of this database,
including recovery of any damages or obtaining other remedies available to
Monsanto.
If you are coming from the for-profit sector and want access to the data, you must contact Monsanto
 directly at: <A href="mailto:jeff.woessner@monsanto.com">jeff.woessner@monsanto.com</A><BR>
<P>If you want to cite Monsanto in your article, please reference following publication.<BR>
Jander, G; Norris, SR; Rounsley, SD; Bush, DF; Levin, IM; Last, RL<BR>
Arabidopsis Map-Based Cloning in the Post-Genome Era<BR>
Plant Physiol, June 2002, 129:440-450<BR>
Download [<a href="http://www.plantphysiol.org/cgi/reprint/129/2/440.pdf">pdf</a>]<br> 
<P>If you have problems with logging in, please contact us at: <a href="javascript:location.href='mailto:curator@arabidopsis.org?SUBJECT=' + document.title + '&BODY=' +'URL: ' + escape(location.href)" onClick="javascript:urchinTracker('/outgoing/curator_at_arabidopsis_org');">curator@arabidopsis.org</a></P>
</dd>
</dl>
<CENTER>

<A href="liability.jsp">General liability statement</A> | <A href="policy.jsp">Privacy policy and Security</A>
<P>
</CENTER>


<p><center>Last modified on September 1, 2006</center></p>

</div> <!--right column-->


<jsp:include page="/jsp/includes/gen_footer.jsp" flush ="true">
<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>


