<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
  </head>

  <body>
    <h1></h1>
<PRE>
CYTOPLASM
PERIPLASM
MEMBRANE
INNER-MEMBRANE
OUTER-MEMBRANE
MITOCHONDRIA
MITOCHONDRIAL-MEMBRANE
CHROMOPLAST
PLASTID
PLASTID-STROMA
PLASTID-OUTER-MEMBRANE
PLASTID-INNER-MEMBRANE
PLASTID-INTERMEMBRANE-SPACE
PLASTID-THYLAKOID
CHLOROPLAST
CHLOROPLAST-OUTER-MEMBRANE
CHLOROPLAST-INNER-MEMBRANE
CHLOROPLAST-INTERMEMBRANE-SPACE
CHLOROPLAST-THYLAKOID
CHLOROPLAST-STROMA
MICROSOME
PEROXISOME
ER
CIS-GOLGI
GOLGI
TRANS-GOLGI
VACUOLE
TONOPLAST
NUCLEUS
NUCLEAR-OUTER-MEMBRANE
NUCLEAR-INNER-MEMBRANE
PERINUCLEAR-SPACE
NUCLEOLUS
PLASMALEMMA
CELL-WALL
</PRE>
    <hr>
    <address><a href="mailto:mueller@aracyc.Stanford.EDU">Lukas Mueller</a></address>
<!-- Created: Thu Aug 29 13:45:04 PDT 2002 -->
<!-- hhmts start -->
Last modified: Thu Aug 29 13:56:45 PDT 2002
<!-- hhmts end -->
  </body>
</html>
