<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%!
String pageName = "TAIR Microarray Tutoriall";
String cssfile="/css/page/pagelevels.css";
%>

<%@ page
errorPage="/jsp/common/gen_error.jsp"
import="org.tair.tfc.*,org.tair.querytools.*, org.tair.utilities.*,java.util.*, java.net.*"
%>


<jsp:include page="/jsp/includes/dyn_header.jsp" flush ="true">
<jsp:param name="pageName" value="<%= pageName %>" />
<jsp:param name="cssfile" value="<%=cssfile %>" />
<jsp:param name="id" value="2024" />
</jsp:include>

<jsp:include page="/jsp/includes/microtutorialSidebar.jsp" flush="true">
<jsp:param name="sidebarName" value="Finding genes that are similarly expressed in multiple experiments"/>
</jsp:include>

<div id="rightcolumn">


<!--content goes  here//-->
<span class="mainheader">Finding genes that are similarly expressed in multiple experiments</span>
<p>There are some basic queries that can be answered by analyzing microarray experimental data such as : What genes in this experiment, or in other experiments behaves similarly to my gene of interest? For a given gene, is its expression correlated with the expression of my gene of interest? What is the expression history of this gene across all experiments? Some of these questions can be answered by querying TAIR's database, others require the use of alternative resources and other tools for analyzing publicly available data.</p>
<p>The emphasis at TAIR has been to incorporate as much microarray data as possible into the database and relate the information to other data objects in TAIR database.Therefore, there are limited resources at TAIR for analyzing microarray experimental data. For the subset of microarray data generated by the Arabidopsis Functional Genomics Consortium, the Expression Viewer is available. This tool allows you to ask the question: For a given subset of experiments, what genes are expressed like my gene of interest. It also can be used to restructure the query to allow different genes to be the query or baseline gene.TAIR's analysis of microarray data has primarily focused on cluster analysis of multiple microarray experiments. The resulting 'mega-clusters' represent genes which show similar patterns of expression across a variety of experiments. TAIR provides the analyzed data and two tools for visualizing the analyzed data, VxInsight (developed at Sandia National Labs) and TreeView (developed by Alok Saldanh at Stanford University, CA).Currently, the megacluster data only includes cDNA array data from experiments conducted by the AFGC. These tools for gene discovery can help identify genes with  similar expression patterns may have a common biological role.</p>
<p> There are other databases which store Arabidopsis microarray data and do provide specialized tools for analyzing the experimental data stored in these databases. We encourage you to examine these resources and make use of their tools.If you are interested in comparing the expression of two genes of interest to see if they are possibly co-expressed, the Two Gene Scatter Plot tool at <a href="http://affymetrix.arabidopsis.info/narrays/experimentbrowse.pl">NASCArrays</a> (CATMA cDNA arrays) or the Gene Correlator at <a href="https://www.genevestigator.ethz.ch/"> GeneVestigator</a> (Affymetrix ATH1 array) can also be used to determine if two genes have  similar expression patterns among the experiments stored in those databases.</p>
<h2>Using the Expression Viewer</h2>
<p>The Expression Viewer software was developed for visualizing cluster data and uses a Pearson correlation coefficient to identify similarly expressed genes. The expression viewer is linked to all array elements that were included on the AFGC cDNA arrays and can be directly accessed from the <a href="/servlets/TairObject?type=array_element&id=6878" target="_blank">Array Element detail page</a>, RNA data section of the <a href="/servlets/TairObject?id=40536&type=locus" target="new">locus detail pages</a> or the microarray element search <a href="element_result.jsp" target="_blank">HTML results page</a>.</p>
<p>This section describes how to access and use the Expression Viewer, starting from the <a href="/servlets/TairObject?id=40536&type=locus" target="new">locus detail pages</a>.</p>
<ol>
<li>Find section Data from Expression Microarrays in the section marked 'RNA data' on the locus detail page.</li>
<p class="sm">Not all locus pages will have this information. If it is absent , this is because the data is not in the database.</p>
<li>Choose one of the array elements with a link to the expression viewer (e.g. H3G4).Click on the Viewer link.</li>
<li>Choose one or more experiment categories to display, such as abiotic treatment. To select multiple categories, hold down the CTRL key (PC) or Apple key (Mac) while making your selections with the mouse. Click Submit.<li>
<p class="sm">The AFGC experiments were assigned to categories,based upon the characteristics of the experiment. Each category was analyzed as separate datasets so that the expression of different genes in SIMILAR experiments could be compared.</p>
</ol>
<h3>Using the results</h3>
<p>The results display color coded values for microarray elements across all of the experiments in the category. The top element is the one you selected, followed by up to 20 of the MOST similarly expressed genes within that category. For each hybridization within the experiments, the expression value is are shown in the colored blocks.Color coded values represent levels of expression where green is most highly repressed and red is most highly induced. Black indicates no change in expression and grey indicates missing values or data that could was not usable (e.g. spot was thrown out). At the end of each row is a brief description of the locus that corresponds to the element. Above each color block is a description of the slide.</p>
<p>From the results page you can:</p>
<ul>
<li>Find information about experimental conditions. Click on the short slide description above the color boxes to view the Microarray Experiment detail pages. From here you can also download the data.</li>
<li>Find information about the locus.Click on the locus name next to the Microarray Element name.</li>
<li>Re-draw the cluster using a different element as the reference.Click anywhere in the color blocks for  the new element of interest. The page will be re-drawn with that element at the top and up to 20 genes that are expressed similarly to the new reference element.</li>
</ul>
<p>For more information about the ExpressionViewer see the <a href="/help/helppages/help_expression.jsp" target="_blank">Help Document</a>.</p>
<h2>Using VxInsight</h2>
<p> VxInsight presents cluster data in a three dimensional view.Genes with similar expression are grouped into mountains which can be zoomed in on to examine the topology in more detail to find more similarly expressed genes. Genes are annotated using information from TAIR about function (GO annotations, AraCyc pathways), localization and other characteristics. You can select sets of interesting genes and save an annotated list onto your personal computer.The version of VxInsight available at TAIR is key locked,meaning it can only be used to visualize a specific data set. The datasets are derived from the AFGC cDNA microarray project that were analyzed using <a href="/tools/bulk/microarray/analysis/index.jsp" target="new">TAIR's large scale microarray analysis pipeline</a>.</p>
<p>Note: VxInsight is only available for the Windows operating system.</p>
<h3>Downloading and installing the software</h3>
<ol>
<li>From the home page click on FTP downloads or the FTP link in the navigation bar.</li>
<li>Navigate to the directory labelled 'Software'. Click on the folder to see the contents.</li>
<li>Locate the folder named VxInsight. Click on the folder to see the contents.</li>
<p class="sm">The directory contains two files. The README is a text file that has instructions on how to install the software. The second file is the executable file (.exe) you need to download.</p>
<li>Click on the vx_keylocked.exe file to download the file onto your personal computer. Save the appliction in a directory.</li>
</ol>
<h3>Downloading and viewing the datasets</h3>
<p>The version of VxInsight will only work with TAIR datasets.These data are located in the FTP site at <a href="ftp://ftp.arabidopsis.org/home/tair/Microarrays/analyzed_data/VxInsight/" target="_blank">ftp://ftp.arabidopsis.org/home/tair/Microarrays/analyzed_data/VxInsight/</a>.</p>
<ol>
<li>From the FTP directory, navigate to the Microarrays directory.</li>
<li>Locate the directory 'analyzed data'.Click to see the contents.</li>
<li>Locate the directory 'VxInsight'.Click to see the contents.</li>
<p class="sm">This directory contains a compressed (.zip) file containing the analyzed data and a README text file that describes the contents of the compressed data file and instructions on downloading.</p>
<li>Click on the file named vx_afgc_397_061703.zip to download it onto your personal computer.</li>
<li>Uncompress the file using WinZip or a similar utility. Make sure that file amd.key should be in the same the directory in which amd.cache file.</li>
<li>Open the VxInsight application.</li>
<li>From the file menu in VxInsight, locate the file named amd.cache and open this file.</li>
</ol>
<p>For more information about using VxInsight see the <a href="http://www.viswave.com/help_doc/VxUsersGuide1_1.pdf">User Guide</a> [PDF format].</p>
<!--
<h3>VxInsight Navigation</h3>
<h3>Interrogating the properties of 'expression mountains'</h3>
<h3>Downloading data from VxInsight</h3>
//-->
<h2>Using Java TreeViewer</h2>
<p>Java TreeViewer is a Java application that runs on your personal computer. Using this software and the pre-computered cluster data from TAIR, you can find genes that are similarly expressed and the utilize the links to TAIR to find corresponding locus and experiment data. It is a platform independant software that runs on Mac, Windows and Unix-based operating systems. This section describes how to download and install the software on your computer and how to find and load the analyzed microarray data.</p>
<h3>Downloading the software and datasets</h3>
<ol>
<li>From the home page click on the link to FTP Downloads or click on the FTP link in the navigation bar at the top of the page.</li>
<li>Find the directory labelled "Software".Click on the folder to see the contents.</li>
<li>Locate the TreeView folder and click to see the contents.</li>
<p class="sm">The file contains a README document which provides information about the content of the files in the directory and instructions on how to install the software.</p>
<li>Click on the link "install.htm".</li>
<li>From the list of installers find the one that is appropriate for your computer.</li>
<p class="sm"> The automatic detection should indicate which installer you should download. Click on the download link.Follow the rest of the instructions for launching the program.</p>
</ol>
<h3>Loading the data</h3>
<p> Once you have downloaded and installed the program, you will need to download and decompress the analyzed data files.</p>
<ol>
<li>Navigate to the FTP directory containing the analyzed data <a href="ftp://ftp.arabidopsis.org/home/tair/Microarrays/analyzed_data/TreeView/">ftp://ftp.arabidopsis.org/home/tair/Microarrays/analyzed_data/TreeView/</a></li>
<li>Download the data file labelled tv_afgc_397_061703.zip to your personal computer.</li>
<li>Uncompress the file using WinZip (PC), StuffitExpander (Mac), unzip (Unix/Linux) or another similar utility.</li>
<li>Launch the Java TreeViewer application.</li>
<li>Under the file menu choose 'Open'.</li>
<li>Navigate to the folder where the uncompressed data files are located.</li>
<li>Select the file with the .cdt suffix.</li>
<p class="sm"> This file contains all of the data which was analyzed with <a href="http://rana.lbl.gov/EisenSoftware.htm" target="_blank">Michael Eisen's Cluster program</a> using standard Pearson correlation and average linking algorithms.</p>
</ol>
</div> <!--right column-->
<jsp:include page="/jsp/includes/gen_footer.jsp" flush ="true">
<jsp:param name="cssfile" value="<%=cssfile %>" />
</jsp:include>