<html>
<head>
<title>TAIR help: Microarray Element Search</title>
<link rel="stylesheet" type="text/css" href="/css/main.css" >
<link rel="stylesheet" type="text/css" href="/css/help.css">
<!-- HEADER using external JavaScript file -->
<jsp:include page="/jsp/includes/helpheader.jsp" flush="true" />
<script>
setPrevious("");
setNext("help_expression.jsp");
writeHeader();
</script>

<!-- End of header -->

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#F5F9FF">



<!-- End of header -->

<ul><h2>Contents</h2>
<li><a href="#mic1">Information About Microarray Elements in TAIR</a>
<li><a href ="#mic3">Understanding the Microarray Elements search results</a>
<li><a href="#mic27">Finding information about experimental conditions for microarray experiments.</a>
<p>
<table width="602" align="center" border="0" cellspacing="0" cellpadding="2">
        <tr>
                <td><H2><a name="mic1"></a>Description of data presented on the Microarray Elements Search Tool</H2>

<br><BR><BR>
<p><font class="cont">The Affymetrix probe set names and sequences were obtained from <a href="http://www.affymetrix.com">Affymetrix</a>. 
The Gene-specific Sequence Tag (GST) names and sequences were obtained from <a href="http://www.catma.org">CATMA</a>.
The AFGC data were obtained from <a href="http://genome-www5.stanford.edu/MicroArray/SMD/">SMD</a> and <a href="/info/2010_projects/comp_proj/AFGC/index.html">AFGC</a>, 
which included array element name (clone ID) and type, sequence information, and organism. The expression profiles were produced by AFGC and are available from 
SMD (Spot History) and TAIR (Expression Viewer). Additional data, such as locus identifiers, annotation, and array element type were generated by TAIR curators. 
</font>
<P>
<font class ="cont"><a name="mic26"></a>The array elements were mapped to AGI (Arabidopsis Genome Initiative) 
locus identifiers using the BLASTN program with e-value cutoff &lt; 1e-6 against the Arabidopsis 
Transcripts dataset, which included mitochondria and chloroplast genes.  
The dataset was produced using the second Arabidopsis genome annotation release from TAIR (version 7.0, April 2007).
</font>
<P>
<font class ="cont">All the data files are available for download from the <a href="ftp://ftp.arabidopsis.org/home/tair/Microarrays/">ftp site</a></font>
<P>
<H2><a name="mic2"></a>TAIR Microarray Elements Statistics</H2>

<table border="1" cellspacing="2" cellpadding="4">
<tr>
<td><b>Specifications</b></td>
<td><b>AFGC</b></td>
<td><b>Affymetrix 8K</b></td>
<td><b>Affymetrix 25K</b></td>
<td><b>CATMA</b></td>
</tr>
<tr>
<td>number of elements</td>
<td>19141</td>
<td>8297</td>
<td>22814</td>
<td>24576</td>
</tr>
<tr>
<td>Arabidopsis elements</td>
<td>18770</td>
<td>8256</td>
<td>22768</td>
<td>24576</td>
</tr>
<tr>
<td>non-Arabidopsis elements</td>
<td>371</td>
<td>41</td>
<td>46</td>
<td>0</td>
</tr>
<tr>
<td>GenBank accessions</td>
<td>15256</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr>
<td>elements with locus assignment</td>
<td>17636</td>
<td>8013</td>
<td>22246</td>
<td>22420</td>
</tr>
<tr>
<td>nuclear loci</td>
<td>17566</td>
<td>8006</td>
<td>22080</td>
<td>22362</td>
</tr>
<tr>
<td>chloroplast loci</td>
<td>64</td>
<td>3</td>
<td>80</td>
<td>8</td>
</tr>
<tr>
<td>mitochondria loci</td>
<td>6</td>
<td>4</td>
<td>86</td>
<td>50</td>
</tr>
<tr>
<td>elements without locus assignment</td>
<td>1505</td>
<td>284</td>
<td>568</td>
<td>2156</td>
</tr>
<tr>
<td>unique loci</td>
<td>11342</td>
<td>7377</td>
<td>21833</td>
<td>20774</td>
</tr>
<tr>
<td>genome mapping date</td>
<td>April 5, 2004</td>
<td>April 5, 2004</td>
<td>April 5, 2004</td>
<td>April 5, 2004</td>
</tr>

</table>
<br>
<h2><a name ="mic3"></a>Microarray Elements Search Results</h2>
<font class="cont"><a name="mic4"></a>After you submit your search parameters the results will be displayed to you in a table format. The following are descriptions of the results fields.</font>
<p>
<h4><a name="mic5"></a>Array Element</h4>
<font class="cont"><a name="mic6"></a>This is the name of the element on an array as given by the manufacturer. For Affymetrix chips, it corresponds to the probe set name.</font>
<p>
<h4><a name="mic7"></a>GenBank Accession</h4>
<a name="mic8"></a><font class="cont">This is the unique identifier to a sequence in GenBank that corresponds to the arrayed gene. Clicking on this link will open a browser window displaying the GenBank record for the nucleotide sequence.</font>
<p>
<h4><a name="mic9"></a>Locus Identifier</h4>
<font class="cont"><a name="mic10"></a>This is the unique identifier for a locus as agreed upon by the AGI, TAIR, MIPS and TIGR. Microarray elements were assigned to a locus based upon nucleotide sequence identity determined using BLAST (<a href="#mic26">See above</a>). 
For each arrayed element, if its sequence matches the AGI Transcripts sequences unambiguously, it is assigned to one locus. If there are multiple loci in this column, it means that either
<ul>
	<li>the array element sequence matches two or more different loci with equal e-values or
	<li>different GenBank sequences for the same array element match to different loci (true for some AFGC clones) or
	<li>the ratio of the e-values for the best BLAST match and its closest match in the list was more than 0.1. 
</ul>
Clicking on the locus name link will take you to the locus detail page in TAIR.</font>
<p>
<h4><a name="mic11"></a>Annotation</h4>
<font class="cont"><a name="mic12"></a>This is the (usually) one line description of the locus provided by the TIGR annotators.</font>
<p>
<h4><a name="mic12"></a>Organism</h4>
<font class="cont"><a name="mic13"></a>The name of the organism from which the microarray element sequence was derived.</font>
<p>
<h4><a name="mic14"></a>Array Element Type (Probe Type)</h4>
<font class="cont"><a name="mic15"></a>Describes the type of molecule from which an array element was derived. Values are: clone, oligonucleotide, DNA fragment.</font>
<p>
<h4><a name="mic16"></a>Is Control</h4>
<font class="cont"><a name="mic17"></a>For each arrayed element this field indicates if the element is considered to be an internal control (yes) or not (no).</font>
<p>
<h4><a name="mic18"></a>Expression Viewer</h4>
<font class="cont"><a name="mic19"></a>Clicking on this link will take you to the microarray expression viewer tool. This tool allows you to select clustered data for that microarray element from  selected AFGC datasets. For more information on the expression viewer see <a href="help_expression.jsp">Expression Viewer Help</a>.</font>
<p>
<h4><a name="mic20"></a>Spot History</h4>
<font class="cont"><a name="mic21"></a>Clicking on this link will take you to a graph display showing the compiled/summarized expression level of that particular element across all experiments. This is an external link to the Stanford Microarray Database (SMD) and only displays results for AFGC microarray experiments. For help with the Spot History see SMD's <a href="http://genome-www5.stanford.edu/cgi-bin/data/spotHistory.pl?state=help" target="new">Spot History Help</a>.</font>
<p>
<h4><a name="mic21"></a>Avg Log Ratio</h4>
<font class="cont"><a name="mic22"></a>Average value of log base 2 of the normalized red/green ratio for a given array element across all experiments stored in TAIR microarray database. 
Currently displays results for AFGC microarray experiments only. All datasets were normalized using print-tip-group 'lowess' method, which has practically removed spatial bias on all arrays 
that had it before (57) and reduced plate bias.</font>
<p>
<h4><a name="mic22"></a>Avg Log Std Err</h4>
<font class="cont"><a name="mic23"></a>This is the standard deviation of the sampling distribution of the mean log base 2 of the normalized red/green ratio for a given array element across all experiments stored in TAIR microarray database. 
</font>
<p>
<h4><a name="mic28"></a>Avg Intensity</h4>
<font class="cont"><a name="mic29"></a>Average value of signal intensity for a given array element across all experiments stored in TAIR microarray database. 
Currently displays results for AFGC microarray experiments only.</font>
<p>
<h4><a name="mic30"></a>Avg Intensity Std Err</h4>
<font class="cont"><a name="mic31"></a>This is the standard deviation of the sampling distribution of the mean signal intensity for a given array element across all experiments stored in TAIR microarray database. 
</font>
<p>
<h4><a name="mic24"></a>Genome Mapping Date</h4>
<font class="cont"><a name="mic25"></a>The date the data analysis for that element was performed to assign array elements to a locus.</font>
<p>
<h2><a name="mic27"></a>Finding information about conditions for microarray experiments.</h2>
<p>
<font class="cont">Microarray Experiements from the AFGC are now searchable from TAIR database using the  <a href="/servlets/Search?type=expr&search_action=new_search">Microarray Experiment Search</a>. For microarray elements included in the Expression Viewer datasets, you can click on the title of the hybridization to link to the experiment detail page (see : <a href="help_expression.jsp">Expression Viewer Help </a> for more information about this tool).</font>
<p>
<h4><a name="mic28"></a>Using the Microarray Elements to find information about  Spot History</h4>
<p>
<font class="cont">Follow the steps below to obtain information about experiments for microarray elements of interest.</font>
<p>
<ol>
<li> From the microarray elements search result page, click on the link under Spot History. This will take you to the Stanford Microarray Database to view the Spot History for that element. 
<li> You should now see a histogram displaying the Normalized Red/Green ratio plotted against Frequency for that specific element.
<li> Place your mouse over any bars you are interested in and click. 
<li> A table will appear to the right of the histogram that displays a list of experiments having values in the specified range(s).
<li>Each experiment has a check box next to the column for experiment number. The default is all experiments selected. Click once to de-select.
<li> Click "Display Data" button to display a list of the selected experiments with more complete information, and further options for viewing data. For more information about how to use the SMD Spot History see <a href="http://genome-www5.stanford.edu/cgi-bin/SMD/spotHistory.pl?state=help">SMD Spot History Help</a>.
<li>You should now see a table listing all of the arrays. 
<li>To obtain information about the experimental conditions go to the 'Options' column and click on the icon labeled 'View'.This action will return a page displaying a description of the array, experimental conditions and other associated data.
</ol>
<p>

                  </font></TD>
          </TR>


<br></TABLE>
<!-- footer using external javascript file starts here -->
<jsp:include page="/jsp/includes/helpfoot.jsp" flush="true" />
<script>
setPrevious("");
setNext("help_expression.jsp");
writeFooter();
</script>
<!-- FOOTER -->


<br></ul></body>
</html>
