<%@page import="org.tair.utilities.*"%>
<html>
<head>
<title>TAIR: Protein Search</title>
<link rel="stylesheet" type="text/css" href="/css/help.css">
<!-- HEADER using external JavaScript file -->
<jsp:include page="/jsp/includes/helpheader.jsp" flush="true" />
<script>
setPrevious("locushistoryhelp.jsp");
setNext("");
writeHeader();
</script>
<!-- End of header -->
</HEAD>
<BODY>
<CENTER>
<table width=600><TR><TD>

  <H2><a name="prot1"></a>Protein Search Help</H2>
		    <BR>
<br>
<H4><a name="prot3"></a>General</H4>
<br>
<p>
The Protein Search allows the retrieval of proteins according to the following predicted protein characteristics:
molecular weight, isoelectric point, presence of protein domains, presence of transmembrane domains and subcellular location.

<p>Because proteins can undergo extensive processing, such as cleavage, glycosylation or phosphorylation, the computational predictions may not reflect the actual biological properties of these proteins.
The results from the Protein Search should therefore be taken with caution.
<br><br>
<a name="outputoptions"></a><H4>Output Options</H4>
<br>
<font class="cont">Output can be in html or plain text. html output links to other TAIR or external services. The output reverts to text when the query matches more than 1000 proteins.
Only the datatypes that are selected on the top of the input form will be output.</font>
<br><br>
<a name="proteincharacteristics"></a><H4>Predicted Protein Characteristics</H4>
    <br>
<font class="cont">The desired characteristics can be entered here. Be sure that all the checkmarks are checked in front of the datatypes that you would like to search. </font>
<br><br>
<a name="limitsearch"></a><H4>Limit Search to Specific Loci</H4>
    <br>
<font class="cont">Enter a list of loci in the text field, or upload a file with a list of loci. The loci can be delimited by return characters, commas or tabs. Example: At1g01010, At1g01020, At1g01030. The search will be performed on this subset of loci instead of all loci.</font>
<br>

<H2><a name="prot2"></a>Information about the Protein Datasets</H2>
<br>
<br>
<H4><a name="prot5"></a>The protein file</H4>
<br>
<font class ="cont">All datasets are based on the protein fasta file, ATH1.pep, made available by TIGR in version 4.0. The release date used is April 16, 2003, unless otherwise noted.</font>
<br><br>
<H4><a name="prot6"></a>Swissprot Ids</H4>
<br>
<font class ="cont">The Swissprot IDs were generated by comparing the TIGR 4.0 protein sequences with Swissprot sequences. Only perfect matches were taken into account. The program used for the comparison was commFasta.pl, version 1.1, which performs a direct string comparison.</font>
<br><BR>
<a name="molecularweights"></a><H4>Predicted Molecular Weights</H4>
<br>
<font class ="cont">The predicted molecular weights of the proteins were calculated using the Bioperl function get_mol_wt (found in the SeqStats object).Input parameters: The ATH1.pep file.Version: Bioperl 0.7.(<a href="http://www.bioperl.org">www.bioperl.org</a>).</font>
<br>
<br>
<a name="isoelectricpoints"></a><H4>Predicted Isoelectic Points</H4>
<br>
<font class ="cont">The predicted isoelectric points were calculated using the iep program in the EMBOSS package.
EMBOSS version: 2.0.1.
Input parameters: ATH1.pep file.
(<a href="http://www.hgmp.mrc.ac.uk/Software/EMBOSS/">www.hgmp.mrc.ac.uk/Software/EMBOSS/</a>).
<br></font>
<br>
<a name="proteindomains"></a><H4>Protein Domains</H4>
<br>
<font class ="cont">The protein domains were analyzed using the InterProScan.pl program and the Interpro databases supplied with the program.
Database version: Interpro 4.0
Input parameters: The ATH1.pep version 4.0 file.
Interpro is on the web at <a href="http://www.ebi.ac.uk/interpro">www.ebi.ac.uk/interpro</a>.</font>
<br>
<br>
<a name="transmembranedomains"></a><H4>Transmembrane Spanning Domains</H4>
<br>
<font class ="cont">The number of transmembrane domains were calculated using the HMMTOP program.
Input parameters: The ATH1.pep protein fasta file.
The HMMTOP program is available from <a href="http://www.enzim.hu/hmmtop/">http://www.enzim.hu/hmmtop/</a>.
(Older versions of the protein search used TMpred for predicting membrane domains. However, HMMTOP seems to give more accurate results. TMPred is available at 
<a href="http://www.isrec.isb-sib.ch/ftp-server/tmpred/">www.isrec.isb-sib.ch/ftp-server/tmpred/</a>).</font>
<br>
<br>
<a name="subcellularlocation"></a><H4>Subcellular Location</H4>
<br>
<font class ="cont">The subcellular locations were predicted using TargetP (thanks Olof!!).
Refer to the <a href="http://www.cbs.dtu.dk/services/TargetP/">TargetP website</a>, which also contains a detailed <a href="http://www.cbs.dtu.dk/services/TargetP/pages/output-descr.html">description</a> of the output.</font>
<br>
<br>
<a name=structural_class></a><H4>Structural Class</H4>
<font class="cont">The structural classification <%=DefinitionsLookup.createPopupLink("StructuralClassType","structural_class_type_id")%> was determined by using hidden Markov models against Structural Classification of Proteins (SCOP) database and kindly provided by Drs Julian Gough and Martin Mandera from SCOP. Refer to the <a href=http://scop.mrc-lmb.cam.ac.uk/scop/>SCOP website</a>, which contains a detailed description of the structural class hierarchy.</font>
<br>
<br>
</TD></TR>
</TABLE> <!-- main document table -->
</center>
<!-- FOOTER -->
<jsp:include page="/jsp/includes/helpfoot.jsp" flush="true" />
<script>
setPrevious("locushistoryhelp.jsp");
setNext("");
writeFooter();
</script>

</body>
</html>