/*
* Copyright (c) 2010 Carnegie Institution for Science. All rights reserved.  
*/
package org.tair.utilities;

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Timestamp;

/**
 * A data transfer object for a page comment.
 * 
 * @author Robert J. Muller
 */
public class Comment implements Serializable {
  /**
   * Serial version UID generated by Eclipse
   */
  private static final long serialVersionUID = -5453118444022174528L;
  /** The comment text */
  private String comment;
  /** The comment ordering number */
  private Long commentNumber;
  /** The community id of the person making the comment */
  private BigInteger communityId;
  /** The name of the person making the comment */
  private String userName;
  /** The date of the comment */
  private Timestamp commentDate;

  /**
   * Get the comment.
   * 
   * @return Returns the comment.
   */
  public String getComment() {
    return comment;
  }

  /**
   * Set the comment.
   * 
   * @param comment The comment to set.
   */
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * Get the commentNumber.
   * 
   * @return Returns the commentNumber.
   */
  public Long getCommentNumber() {
    return commentNumber;
  }

  /**
   * Set the commentNumber.
   * 
   * @param commentNumber The commentNumber to set.
   */
  public void setCommentNumber(Long commentNumber) {
    this.commentNumber = commentNumber;
  }

  /**
   * Get the communityId.
   * 
   * @return Returns the communityId.
   */
  public BigInteger getCommunityId() {
    return communityId;
  }

  /**
   * Set the communityId.
   * 
   * @param communityId The communityId to set.
   */
  public void setCommunityId(BigInteger communityId) {
    this.communityId = communityId;
  }

  /**
   * Get the userName.
   * @return Returns the userName.
   */
  public String getUserName() {
    return userName;
  }

  /**
   * Set the userName.
   * @param userName The userName to set.
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * Get the commentDate.
   * @return Returns the commentDate.
   */
  public Timestamp getCommentDate() {
    return commentDate;
  }

  /**
   * Set the commentDate.
   * @param commentDate The commentDate to set.
   */
  public void setCommentDate(Timestamp commentDate) {
    this.commentDate = commentDate;
  }

}
